language: node_js
node_js:
  - "0.10.32"

install:
  - "cat test/lib/sample_login_data.js | sed \"s/org: \'dev\'/org: \'$demo_dev\'/\" > test/lib/login_data.js"
  - "tail test/lib/login_data.js"
  - "npm install"
  - "wget xtuple.com/bootstrap -qO- | sudo bash"
  - "npm install -g xtuple-server"
  - "sudo xtuple-server install-dev --xt-name dev --xt-version v4.7.0 --xt-demo"

before_script:
  - "n 0.10.32"
  - "npm start &"
  - "sleep 10"

script:
  - "npm run-script test-datasource"
  - "npm run-script test"
  - "npm run-script jshint"
