language: node_js
node_js:
  - "0.10"

install:
  - "wget xtuple.com/bootstrap -qO- | sudo bash"
  - "npm install"
  - "npm install -g xtuple-server"
  - "sudo xtuple-server install-dev --xt-name dev --xt-version v4.7.0 --xt-demo"

before_script:
  - "npm start &"
  - "sleep 10"

script:
  - "npm run-script test-datasource"
  - "npm run-script test"
  - "npm run-script jshint"
