language: c

install:
  - npm install
  - wget xtuple.com/bootstrap -qO- | sudo bash
  - /usr/local/bin/npm install -g xtuple-server
  - sudo xtuple-server install-dev --xt-version 4_8_x --xt-demo

before_script:
  - n 0.10.32
  - /usr/local/bin/npm start > thelog.txt &
  - sleep 10

script:
  - /usr/local/bin/npm run-script test-datasource
  - /usr/local/bin/npm run-script test
  - /usr/local/bin/npm run-script jshint

after_failure:
  - sudo tail -n 100000 thelog.txt
  - sudo ls -l /var
  - sudo ls -l /var/log
  - sudo ls -l /var/log/xtuple
  - sudo tail -n 100000 /var/log/xtuple/travis-v470-dev-forever.log
