language: c

before_install:
  - rm -rf ~/.nvm
  - wget git.io/hikK5g -qO- | sudo bash

install:
  - n latest
  - npm install xtuple-server -g
  - n stable

before_script:
  - sudo xtuple-server install-pilot --xt-demo --pg-worldlogin
  - npm run test-build
  - npm start &
  - sleep 10

script:
  - npm test
  - npm run test-datasource
  - npm run jshint

after_failure:
  - env
  - cat test/lib/login_data.json
  - cat node-datasource/config.js
  - cat npm-debug.log
